query GET_CHARACTERS ($page: Int!, $filter: { name: String}) {
  characters(page: $page, filter: $filter) {
    rresults {
      id
      name
      species
      episode {
        episode
      }
    }
  }
}