query GET_CHARACTERS ($page: Int!, $filter: String) {
  characters(page: $page, filter: { name: $filter}) {
    rresults {
      id
      name
      species
      episode {
        episode
      }
    }
  }
}